/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteWhatIsPackagingRouteImport } from './routes/_site/what-is-packaging'
import { Route as SiteProductsRouteImport } from './routes/_site/products'
import { Route as SiteInfrastructureRouteImport } from './routes/_site/infrastructure'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCareersRouteImport } from './routes/_site/careers'
import { Route as SiteAboutRouteImport } from './routes/_site/about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWhatIsPackagingRoute = SiteWhatIsPackagingRouteImport.update({
  id: '/what-is-packaging',
  path: '/what-is-packaging',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInfrastructureRoute = SiteInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersRoute = SiteCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/careers': typeof SiteCareersRoute
  '/contact': typeof SiteContactRoute
  '/infrastructure': typeof SiteInfrastructureRoute
  '/products': typeof SiteProductsRoute
  '/what-is-packaging': typeof SiteWhatIsPackagingRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/careers': typeof SiteCareersRoute
  '/contact': typeof SiteContactRoute
  '/infrastructure': typeof SiteInfrastructureRoute
  '/products': typeof SiteProductsRoute
  '/what-is-packaging': typeof SiteWhatIsPackagingRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/careers': typeof SiteCareersRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/infrastructure': typeof SiteInfrastructureRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/what-is-packaging': typeof SiteWhatIsPackagingRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/infrastructure'
    | '/products'
    | '/what-is-packaging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/careers'
    | '/contact'
    | '/infrastructure'
    | '/products'
    | '/what-is-packaging'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/careers'
    | '/_site/contact'
    | '/_site/infrastructure'
    | '/_site/products'
    | '/_site/what-is-packaging'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/what-is-packaging': {
      id: '/_site/what-is-packaging'
      path: '/what-is-packaging'
      fullPath: '/what-is-packaging'
      preLoaderRoute: typeof SiteWhatIsPackagingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/infrastructure': {
      id: '/_site/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof SiteInfrastructureRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers': {
      id: '/_site/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof SiteCareersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCareersRoute: typeof SiteCareersRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteInfrastructureRoute: typeof SiteInfrastructureRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteWhatIsPackagingRoute: typeof SiteWhatIsPackagingRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCareersRoute: SiteCareersRoute,
  SiteContactRoute: SiteContactRoute,
  SiteInfrastructureRoute: SiteInfrastructureRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteWhatIsPackagingRoute: SiteWhatIsPackagingRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
